server:
  port: 8004

management:
  security:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://discovery:8761}/eureka/

## Mybatis 配置
mybatis:
  typeAliasesPackage: cn.sm.alivepush.contract.entity
  mapperLocations: classpath:mapper/*.xml

## Mysql
spring:
  datasource:
    url: jdbc:mysql://39.108.11.254:3306/world?characterEncoding=utf8
    username: root
    password: Jgxy@1234#
    driver-class-name: com.mysql.jdbc.Driver