server:
  port: 8003
management:
  security:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://discovery:8761}/eureka/

ribbon:
  eureka:
    enable: true