server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://discovery:8761}/eureka/

management.security.enabled: false
spring:
  application:
    name: monitor
#  boot:
#    admin:
#      routes:
#        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
#      turbine:
#        clusters: default
#        location: turbine